name: QA

on:
  workflow_dispatch:
  push:
    branches: [ main, '[0-9]+.[0-9]' ]
  pull_request:

permissions:
  contents: read

# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  static-analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-php
        with:
          php-version: '8.1'

      - name: Static Code Analysis with phpstan
        run: ./scripts/analyse
        shell: bash

  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: ['8.1', '8.2']
        testsuite: ['unit', 'integration']
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-php
        with:
          php-version: ${{ matrix.php-version }}

      - name: Testsuite "${{ matrix.testsuite }}" with phpunit
        run: |
          ./scripts/test --testsuite ${{ matrix.testsuite }}
